version: '3'
services:
  meuprimeirocrudgo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb:mongodb:27017
      DB_NAME: golang-crud
      MONGODB_COLLECTION: users
      JWT_SECRET_KEY: kjahdkajhds
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - meuprimeirocrudgo_network
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - meuprimeirocrudgo_network

networks:
  meuprimeirocrudgo_network:
  
